name: 'Terraform Destroy'
env:
  TF_VAR_bkt: ${{ secrets.bkt }}

on:
  workflow_run:
    workflows: ["Terraform Create"]  # Triggered when the "Create Resources" workflow completes
    types:
      - completed 
  workflow_dispatch:  # Allow manual trigger
  
jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: ${{ github.event.workflow_run.conclusion }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Debug GitHub Event
        run: |
             echo "GitHub Event Name: $GITHUB_EVENT_NAME"
             echo "Conclusion of the Create Workflow: ${{ github.event.workflow_run.conclusion }}"

      - name: Wait for 5 minutes before destroy
        run: |
          echo "Waiting for 5 minutes..."
          sleep 300  # Wait for 5 minutes (300 seconds)

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
