name: 'Terraform Destroy'
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: 'us-east-1'
    TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_ssh_public_key }}

on:
  workflow_dispatch:
    branches: 
      - main

permissions:
  contents: read

jobs:
  terraform_validate:
    name: 'Terraform Init'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform fmt
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

  terraform_destroy_plan:
    name: 'Terraform Destroy Plan'
    runs-on: ubuntu-latest
    needs: terraform_validate  # Ensure this job runs after the init job
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy Plan
        run:  terraform plan -destroy -input=false

  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: terraform_destroy_plan
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
