name: 'Terraform Destroy'
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: 'us-east-1'
    TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_ssh_public_key }}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-terraform-create:
    name: Check "Terraform Create" Success
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        uses: cli/cli-action@v1

      - name: Check last successful run of "Terraform Create"
        id: check_status
        run: |
          RUN_ID=$(gh run list --workflow="Terraform Create" --limit 1 --json status,conclusion --jq '.[0].status + ":" + .[0].conclusion')
          echo "Last run status: $RUN_ID"
          if [[ "$RUN_ID" != "completed:success" ]]; then
            echo "❌ Last run of 'Terraform Create' did not complete successfully."
            exit 1
          fi

  terraform_validate:
    name: 'Terraform Init'
    runs-on: ubuntu-latest
    needs: check-terraform-create
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform fmt
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

  terraform_destroy_plan:
    name: 'Terraform Destroy Plan'
    runs-on: ubuntu-latest
    needs: terraform_validate  # Ensure this job runs after the init job
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy Plan
        run:  terraform plan -destroy -input=false

  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: terraform_destroy_plan
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
