name: 'Terraform Destroy'
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: 'us-east-1'
    TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_ssh_public_key }}

on:
  workflow_dispatch:  # Allow manual trigger

terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: terraform_apply
    environment: ${{ github.event.workflow_run.output.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Debug GitHub Event
        run: |
             echo "GitHub Event Name: $GITHUB_EVENT_NAME"

      - name: Wait for 5 minutes before destroy
        run: |
          echo "Waiting for 5 minutes..."
          sleep 300  # Wait for 5 minutes (300 seconds)

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false